id: I41487471
ocr_import_info:
  timestamp: '2023-06-28T13:06:54.985307+00:00'
  batch_id: batch-44d7
  ocr_engine: GoogleVisionEngine
  ocr_model_type: builtin/weekly
  ocr_lang_hint: ''
  software_id: ocr-pipelines@v0.1.11
  sponsor: PechaJobs
  sponsor_consent: true
  op_import_options: {}
  op_import_version: 0.11.7
default_language: bo
source: https://library.bdrc.io
initial_creation_type: ocr
imported: 2023-06-28 14:56:46.056704+00:00
last_modified: 2023-06-28 14:56:46.056712+00:00
source_metadata:
  id: http://purl.bdrc.io/resource/W29186
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW29186
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: གསུང་འབུམ། ཡེ་ཤེས་རྒྱ་མཚོ།
  languages:
  - bo
  author: ཡེ་ཤེས་རྒྱ་མཚོ།
statistics:
  ocr_word_mean_confidence_index: 0.9975483159272046
  ocr_word_median_confidence_index: 1.0
bases:
  I00EGS1017110:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017110
      total_pages: 614
      volume_number: 3
      volume_pages_bdrc_intro: 2
    order: 3
    base_file: I00EGS1017110.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.996972997078932
  I00EGS1017112:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017112
      total_pages: 646
      volume_number: 5
      volume_pages_bdrc_intro: 2
    order: 5
    base_file: I00EGS1017112.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9976743065685261
  I00EGS1017109:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017109
      total_pages: 694
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I00EGS1017109.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9981019265311885
  I00EGS1017111:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017111
      total_pages: 622
      volume_number: 4
      volume_pages_bdrc_intro: 2
    order: 4
    base_file: I00EGS1017111.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9974539566214857
  I00EGS1017108:
    source_metadata:
      id: http://purl.bdrc.io/resource/I00EGS1017108
      total_pages: 620
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I00EGS1017108.txt
    statistics:
      ocr_word_median_confidence_index: 1.0
      ocr_word_mean_confidence_index: 0.9974931651918079
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
